### ISSUE TITLE
WebStore front deployment from CSP admin site error.

### ISSUE THREAD

**Issue by cdkimmel** [microsoft/Partner-Center-Storefront#20]
Issue : Unable to deploy WebStore front.

Error : The Website is still under construction. Please visit later. 
And when tried to configure the storefront with organization name or when tried to login it gives an error “Object reference not set to an instance of an object”

Troubleshooting performed : 

•	Tried with different Azure subscriptions and tried multiple times with different storefront names. 
•	All the deployment that we tried has created Storage account, App Service, App Service plan resources ( Azure – All resources )
•	Tried update from the Partner Center portal also tried manual sync from App Service – Deployment Center – Sync.
•	The Sync get successful but the issue still remains.

**Comment by isaiahwilliams** [comment]
@cdkimmel can you share a screenshot of the API permissions you configured for the Azure AD application that was used during the deployment?

**Comment by isaiahwilliams** [comment]
@cdkimmel are you still having issues?

**Comment by cdkimmel** [comment]
Yes, we’re still not able to publish the Web Storefront through the partner portal.  This is the link to the latest attempted deployment:

https://sparkhound-csp.azurewebsites.net/

At the initial page, we get this:
[cid:image001.png@01D5BFC5.02812BE0]

I’ll try to login and get this:
[cid:image002.png@01D5BFC5.02812BE0]

**Comment by isaiahwilliams** [comment]
@cdkimmel thank you for sharing this information. To help us rule out a permissions issue can you browse to the following link and authenticate? 

https://login.microsoftonline.com/common/oauth2/authorize?response_type=id_token&client_id=932a52c0-4bc4-4047-803c-c2b7f92441e5&redirect_uri=https%3A%2F%2Fsparkhound-csp.azurewebsites.net&prompt=admin_consent

This will perform an admin consent, which will ensure that you are not encountering a consent issue. If this does not work can you share the full error message you are receiving, since you have deployed the latest version of the code it should be returning a different error now.

**Comment by cdkimmel** [comment]
I get this when I click the logon link.

[cid:image001.png@01D5C171.E281CBC0]

**Comment by cdkimmel** [comment]
I’m just now seeing this.  I didn’t “configure” anything other than try to deploy the site from the partner portal.

**Comment by isaiahwilliams** [comment]
Please let us know if you are still having an issue.
